languageCode = "en-gb"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://plopcas.github.io/blog/"
canonifyurls = true
title = "Pedro Lopez"
author = "admin"
theme = "pixyllalt"
disqusShortname = "plopcas"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  googleAnalytics = "UA-121538856-1"
  twitter_username = "plopcas"
  paginate = true
  description = "Management and software engineering blog"
  github = "https://github.com/plopcas"
  twitter = "https://twitter.com/plopcas"
  linkedin = "https://www.linkedin.com/in/plopcas"
